remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: Uncountable ideas, enumerated
description: Making computers useful
author: Ross Johnstone

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      show_date: true
