remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: Uncountable ideas, enumerated
description: Making computers useful

author:
  name     : "Ross H. Johnstone"
  # avatar   : "/assets/images/bio-photo.jpg"
  bio      : "Mathematician and machine learning engineer."
  location : "Tokyo, Japan"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      show_date: true

atom_feed:
  hide: true
