remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: Uncountable ideas, enumerated
# description: Making computers useful

author:
  name     : "Ross H. Johnstone"
  # avatar   : "/assets/images/bio-photo.jpg"
  bio      : "Mathematician and machine learning engineer."
  location : "Tokyo, Japan"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:contact@rossjohnst.one"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rhjohnstone"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/rhjohnstone"
    - label: "Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=kHcq3cYAAAAJ"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

atom_feed:
  hide: true

include: ["_pages"]
paginate: 5
paginate_path: /blog/page:num
